/**
 * Ruxsat kodlari — backend `uz.shinamagazin.api.enums.PermissionCode` bilan MOS bo'lishi shart.
 *
 * Ilgari bu xarita 600 qatorli `hooks/usePermission.ts` ichida turardi (hook'ning o'zi
 * o'qib bo'lmas darajada uzun edi). Endi alohida modul; `npm run check:permissions`
 * (va CI) ikkala tomonning mosligini tekshiradi.
 */
export const PermissionCode = {
  // DASHBOARD
  DASHBOARD_VIEW: 'DASHBOARD_VIEW',

  // PRODUCTS
  PRODUCTS_VIEW: 'PRODUCTS_VIEW',
  PRODUCTS_CREATE: 'PRODUCTS_CREATE',
  PRODUCTS_UPDATE: 'PRODUCTS_UPDATE',
  PRODUCTS_DELETE: 'PRODUCTS_DELETE',

  // BRANDS
  BRANDS_VIEW: 'BRANDS_VIEW',
  BRANDS_CREATE: 'BRANDS_CREATE',
  BRANDS_UPDATE: 'BRANDS_UPDATE',
  BRANDS_DELETE: 'BRANDS_DELETE',

  // CATEGORIES
  CATEGORIES_VIEW: 'CATEGORIES_VIEW',
  CATEGORIES_CREATE: 'CATEGORIES_CREATE',
  CATEGORIES_UPDATE: 'CATEGORIES_UPDATE',
  CATEGORIES_DELETE: 'CATEGORIES_DELETE',

  // SALES
  SALES_VIEW: 'SALES_VIEW',
  SALES_CREATE: 'SALES_CREATE',
  SALES_UPDATE: 'SALES_UPDATE',
  SALES_DELETE: 'SALES_DELETE',
  SALES_REFUND: 'SALES_REFUND',

  // CUSTOMERS
  CUSTOMERS_VIEW: 'CUSTOMERS_VIEW',
  CUSTOMERS_CREATE: 'CUSTOMERS_CREATE',
  CUSTOMERS_UPDATE: 'CUSTOMERS_UPDATE',
  CUSTOMERS_DELETE: 'CUSTOMERS_DELETE',

  // DEBTS
  DEBTS_VIEW: 'DEBTS_VIEW',
  DEBTS_CREATE: 'DEBTS_CREATE',
  DEBTS_UPDATE: 'DEBTS_UPDATE',
  DEBTS_DELETE: 'DEBTS_DELETE',
  DEBTS_PAY: 'DEBTS_PAY',

  // WAREHOUSE
  WAREHOUSE_VIEW: 'WAREHOUSE_VIEW',
  WAREHOUSE_CREATE: 'WAREHOUSE_CREATE',
  WAREHOUSE_UPDATE: 'WAREHOUSE_UPDATE',
  WAREHOUSE_DELETE: 'WAREHOUSE_DELETE',
  WAREHOUSE_ADJUST: 'WAREHOUSE_ADJUST',

  // SUPPLIERS
  SUPPLIERS_VIEW: 'SUPPLIERS_VIEW',
  SUPPLIERS_CREATE: 'SUPPLIERS_CREATE',
  SUPPLIERS_UPDATE: 'SUPPLIERS_UPDATE',
  SUPPLIERS_DELETE: 'SUPPLIERS_DELETE',

  // PURCHASES
  PURCHASES_VIEW: 'PURCHASES_VIEW',
  PURCHASES_CREATE: 'PURCHASES_CREATE',
  PURCHASES_UPDATE: 'PURCHASES_UPDATE',
  PURCHASES_DELETE: 'PURCHASES_DELETE',
  PURCHASES_RECEIVE: 'PURCHASES_RECEIVE',
  PURCHASES_RETURN: 'PURCHASES_RETURN',

  // REPORTS
  REPORTS_VIEW_SALES: 'REPORTS_VIEW_SALES',
  REPORTS_VIEW_WAREHOUSE: 'REPORTS_VIEW_WAREHOUSE',
  REPORTS_VIEW_DEBTS: 'REPORTS_VIEW_DEBTS',
  REPORTS_EXPORT: 'REPORTS_EXPORT',

  // EMPLOYEES
  EMPLOYEES_VIEW: 'EMPLOYEES_VIEW',
  EMPLOYEES_CREATE: 'EMPLOYEES_CREATE',
  EMPLOYEES_UPDATE: 'EMPLOYEES_UPDATE',
  EMPLOYEES_DELETE: 'EMPLOYEES_DELETE',
  EMPLOYEES_CHANGE_ROLE: 'EMPLOYEES_CHANGE_ROLE',
  EMPLOYEES_MANAGE_ACCESS: 'EMPLOYEES_MANAGE_ACCESS',

  // USERS
  USERS_VIEW: 'USERS_VIEW',
  USERS_CREATE: 'USERS_CREATE',
  USERS_UPDATE: 'USERS_UPDATE',
  USERS_DELETE: 'USERS_DELETE',
  USERS_CHANGE_ROLE: 'USERS_CHANGE_ROLE',

  // SETTINGS
  SETTINGS_VIEW: 'SETTINGS_VIEW',
  SETTINGS_UPDATE: 'SETTINGS_UPDATE',

  // SHIFTS — kassa smenasi va Z-hisobot
  SHIFTS_VIEW: 'SHIFTS_VIEW',
  SHIFTS_MANAGE: 'SHIFTS_MANAGE',

  // EXPENSES — xarajatlar va sof foyda (P&L)
  EXPENSES_VIEW: 'EXPENSES_VIEW',
  EXPENSES_CREATE: 'EXPENSES_CREATE',
  EXPENSES_UPDATE: 'EXPENSES_UPDATE',
  EXPENSES_DELETE: 'EXPENSES_DELETE',

  // NOTIFICATIONS
  NOTIFICATIONS_VIEW: 'NOTIFICATIONS_VIEW',
  NOTIFICATIONS_MANAGE: 'NOTIFICATIONS_MANAGE',

  // ROLES
  ROLES_VIEW: 'ROLES_VIEW',
  ROLES_CREATE: 'ROLES_CREATE',
  ROLES_UPDATE: 'ROLES_UPDATE',
  ROLES_DELETE: 'ROLES_DELETE',
} as const;

export type PermissionCodeType = (typeof PermissionCode)[keyof typeof PermissionCode];
